import { cookies } from 'next/dist/client/components/headers'
import { Providers } from './Redux/provider'
import Footer from './components/Footer'
import Header from './components/Header'
import ReactQueryProvider from './components/ReactQueryProvider'
import './globals.css'

// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  let mode = cookies().get('mode')
  console.log(mode?.value);

  return (
    <html lang="ko">
      <meta name="theme-color" content="#ffffff" />
      <link rel="manifest" href="/manifest.json" />
      <body className={`relative ${ mode?.value != undefined && mode?.value == 'darkMode' ? ' darkMode' : 'lightMode' }`}>
        <Providers>
          <ReactQueryProvider>
            <Header />
              {children}
            <Footer />
          </ReactQueryProvider>
        </Providers>
      </body>
    </html>
  )
}
